name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * 1,4' # 9 AM UTC Mon & Thu
  workflow_dispatch: # Manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: cron
    steps:
      - name: Run Node script to ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          sudo apt-get install -y nodejs npm
          npm install @supabase/supabase-js --force
          node -e "
          (async () => {
            const { createClient } = require('@supabase/supabase-js');
            const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
            const { data, error } = await supabase.from('users').select('*').limit(1);
            if (error) throw error;
            console.log('Ping successful:', data);
          })();
          "
